name: "Build Executables"

on:
  pull_request:
    branches:
    - main

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install necessary Python packages
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
        
      - name: Create executable
        run: pyinstaller -F --distpath 'bin/linux/' -n 'pixel-palace' src/main.py
      
      - name: Commit executable
        run: |
          # ensure that ga-build is deleted if a previous run did not finish
          git branch -D ga-build &>/dev/null || true
          git push origin --delete ga-build &>/dev/null || true
          git switch -c ga-build
          git add bin/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'GitHub Action: build Linux executable'
          git push --set-upstream origin ga-build

  build_macos:
    needs: build_linux
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install necessary Python packages
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
        
      - name: Create executable
        run: pyinstaller -F --distpath 'bin/macos/' -n 'pixel-palace' src/main.py
      
      - name: Commit executable
        run: |
          git switch ga-build
          git add bin/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'GitHub Action: build macOS executable'
          git push

  build_windows:
    needs: [build_linux, build_macos]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install necessary Python packages
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
        
      - name: Create executable
        run: pyinstaller -F --distpath 'bin/windows/' -n 'pixel-palace' src/main.py
      
      - name: Commit executable
        run: |
          git switch ga-build
          git add bin/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'GitHub Action: build Windows executable'
      
      - name: Squash build commits
        run: |
          git reset --soft HEAD~3
          git commit -m 'Github Action: build executables'
          git switch -
          git merge ga-build
          git push --force
          git branch -D ga-build
          git push origin --delete ga-build
